# Generated by Django 5.2.10 on 2026-03-02 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_backfill_riderprofile_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderweeklyreport',
            name='facility',
            field=models.ForeignKey(blank=True, help_text='Facility in the report’s district.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rider_weekly_reports', to='operations.facility'),
        ),
    ]
