# Generated by Django 5.2.10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0010_bike_functionality'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderweeklyreport',
            name='is_relief_rider',
            field=models.BooleanField(default=False, help_text='Whether this report is for a relief rider (someone other than the assigned rider).'),
        ),
    ]
