# Generated by Django 5.2.10 on 2026-03-09 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0018_samplerejection_and_migrate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samplerejection',
            name='test_type',
        ),
    ]
