# Generated by Django 5.2.10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0023_remove_samplerejection_quality_qty_transit'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderweeklyreport',
            name='client_uuid',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
