from .auth_views import LoginView, LogoutView, RoleRedirectView
from .pc_report_views import (
    PCReportEditView,
    ReportAuditLogListView,
    ReportEditHistoryView,
    ReportReviewGroupView,
    ReportReviewView,
    ReportStartReviewGroupView,
    ReportStartReviewView,
)
from .report_export_views import ReportExportView
from .report_views import (
    ReportFacilitiesAjaxView,
    ReportSubmitView,
    RiderRegisterDeviceView,
    RiderReportCreateView,
    RiderReportDetailView,
    RiderReportEditView,
    RiderReportListView,
    RiderSyncView,
)
from .pc_management_views import (
    BikeCreateView,
    BikeDeleteView,
    BikeListView,
    BikeUpdateView,
    CarCreateView,
    CarDeleteView,
    CarListView,
    CarUpdateView,
    DriverCreateView,
    DriverDeactivateView,
    DriverListView,
    DriverUpdateView,
    FacilityCreateView,
    FacilityDeleteView,
    FacilityListView,
    FacilityUpdateView,
    HubCreateView,
    HubDeleteView,
    HubListView,
    HubUpdateView,
    PCManageIndexView,
    RiderCreateView,
    RiderDeactivateView,
    RiderListView,
    RiderUpdateView,
)
from .pwa_views import service_worker
from .pc_transport_stats_views import PCDistrictWeeklyTransportStatView
from .stub_views import NotRestoredView

__all__ = [
    "LoginView",
    "LogoutView",
    "RoleRedirectView",
    "RiderReportListView",
    "RiderReportCreateView",
    "RiderReportDetailView",
    "RiderReportEditView",
    "ReportSubmitView",
    "ReportFacilitiesAjaxView",
    "RiderRegisterDeviceView",
    "RiderSyncView",
    "PCReportEditView",
    "ReportEditHistoryView",
    "ReportStartReviewView",
    "ReportReviewView",
    "ReportStartReviewGroupView",
    "ReportReviewGroupView",
    "ReportAuditLogListView",
    "ReportExportView",
    "NotRestoredView",
    "service_worker",
    "PCManageIndexView",
    "BikeListView",
    "BikeCreateView",
    "BikeUpdateView",
    "BikeDeleteView",
    "CarListView",
    "CarCreateView",
    "CarUpdateView",
    "CarDeleteView",
    "FacilityListView",
    "FacilityCreateView",
    "FacilityUpdateView",
    "FacilityDeleteView",
    "HubListView",
    "HubCreateView",
    "HubUpdateView",
    "HubDeleteView",
    "RiderListView",
    "RiderCreateView",
    "RiderUpdateView",
    "RiderDeactivateView",
    "DriverListView",
    "DriverCreateView",
    "DriverUpdateView",
    "DriverDeactivateView",
    "PCDistrictWeeklyTransportStatView",
]
