# Generated by Django 4.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderweeklyreport',
            name='pepfar_support_type',
            field=models.CharField(
                blank=True,
                choices=[('TA-SDI', 'TA-SDI'), ('DSD', 'DSD')],
                max_length=20,
            ),
        ),
    ]
