# Generated by Django 5.2.10 on 2026-03-02 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_add_report_facility'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='riderweeklyreport',
            options={'ordering': ['-week', '-created_at', 'rider'], 'verbose_name': 'Rider Weekly Report', 'verbose_name_plural': 'Rider Weekly Reports'},
        ),
        migrations.RemoveConstraint(
            model_name='riderweeklyreport',
            name='unique_rider_week',
        ),
    ]
