# Generated by Django 5.2.10 on 2026-03-11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0022_transport_route_type_and_lab_fks'),
    ]

    operations = [
        migrations.RemoveField(model_name='samplerejection', name='rejected_quality_compromised'),
        migrations.RemoveField(model_name='samplerejection', name='rejected_quantity_insufficient'),
        migrations.RemoveField(model_name='samplerejection', name='rejected_transit_damage'),
    ]
