# Generated by Django 5.2.12 on 2026-03-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0030_referredsample_comments_referredsample_from_facility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderweeklyreport',
            name='average_datalogger_temperature',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Average datalogger temperature for this record.', max_digits=6, null=True),
        ),
    ]
