# Generated by Django 5.2.12 on 2026-04-08 08:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderTripEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_uuid', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('entry_date', models.DateField(blank=True, null=True)),
                ('vl_blood_plasma', models.PositiveIntegerField(default=0)),
                ('vl_dbs', models.PositiveIntegerField(default=0)),
                ('eid_blood', models.PositiveIntegerField(default=0)),
                ('eid_dbs', models.PositiveIntegerField(default=0)),
                ('sputum', models.PositiveIntegerField(default=0)),
                ('sputum_culture_dr', models.PositiveIntegerField(default=0)),
                ('hpv', models.PositiveIntegerField(default=0)),
                ('specimens_other_specify', models.CharField(blank=True, max_length=255)),
                ('results_vl_blood_plasma', models.PositiveIntegerField(default=0)),
                ('results_vl_dbs', models.PositiveIntegerField(default=0)),
                ('results_eid_blood', models.PositiveIntegerField(default=0)),
                ('results_eid_dbs', models.PositiveIntegerField(default=0)),
                ('results_sputum', models.PositiveIntegerField(default=0)),
                ('results_sputum_culture_dr', models.PositiveIntegerField(default=0)),
                ('results_hpv', models.PositiveIntegerField(default=0)),
                ('results_other_specify', models.CharField(blank=True, max_length=255)),
                ('fuel_allocated', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fuel_used', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('distance_travelled', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_entries', to='operations.riderweeklyreport')),
            ],
            options={
                'ordering': ['sequence', 'id'],
                'constraints': [models.UniqueConstraint(fields=('report', 'row_uuid'), name='uniq_trip_row_uuid_per_report')],
            },
        ),
    ]
