# Generated by Django 5.2.12 on 2026-04-08 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_ridertripentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bikes', to='operations.district'),
        ),
        migrations.AddField(
            model_name='district',
            name='support_type',
            field=models.CharField(blank=True, choices=[('DSD', 'DSD'), ('TA-SDI', 'TA-SDI'), ('TAT', 'TAT'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='riders', to='operations.province'),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='support_type',
            field=models.CharField(blank=True, choices=[('DSD', 'DSD'), ('TA-SDI', 'TA-SDI'), ('TAT', 'TAT'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
