# Generated by Django 5.2.12 on 2026-04-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_bike_district_district_support_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='support_type',
            field=models.CharField(blank=True, choices=[('DSD', 'DSD'), ('TA-SDI', 'TA-SDI'), ('TAT', 'TAT'), ('OTHER', 'Other')], help_text='PEPFAR support model for this site (e.g. TA-SDI).', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='facility',
            unique_together={('district', 'name')},
        ),
    ]
