# Generated by Django 5.2.12 on 2026-04-08 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_facility_support_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridertripentry',
            name='destination_facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trip_destinations', to='operations.facility'),
        ),
        migrations.AddField(
            model_name='ridertripentry',
            name='origin_facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trip_origins', to='operations.facility'),
        ),
        migrations.AddField(
            model_name='ridertripentry',
            name='route_kind',
            field=models.CharField(blank=True, choices=[('facility_to_facility', 'Facility to facility'), ('facility_to_lab', 'Facility to lab'), ('lab_to_facility', 'Lab to facility'), ('hub_to_hub', 'Hub to hub'), ('hub_to_lab', 'Hub to lab'), ('lab_to_hub', 'Lab to hub'), ('lab_to_lab', 'Lab to lab')], max_length=40),
        ),
        migrations.AddField(
            model_name='ridertripentry',
            name='visit_purpose',
            field=models.CharField(blank=True, choices=[('sample_collection', 'Sample collection'), ('sample_delivery', 'Sample delivery')], max_length=32),
        ),
    ]
