# Generated by Django 5.2.12 on 2026-04-08 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_ridertripentry_routing_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleRejection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_type', models.CharField(choices=[('vl_plasma', 'VL Plasma'), ('vl_dbs', 'VL DBS'), ('eid_blood', 'EID Blood'), ('eid_dbs', 'EID DBS'), ('sputum', 'Sputum'), ('sputum_culture_dr', 'Sputum Culture DR'), ('hpv', 'HPV'), ('other', 'Other')], max_length=50)),
                ('rejected_total', models.PositiveIntegerField(default=0, help_text='Total rejected for this sample type.')),
                ('rejected_too_old', models.PositiveIntegerField(default=0)),
                ('rejected_patient_info_mismatch', models.PositiveIntegerField(default=0)),
                ('rejected_request_form_missing', models.PositiveIntegerField(default=0)),
                ('rejected_sample_missing', models.PositiveIntegerField(default=0)),
                ('rejected_other', models.PositiveIntegerField(default=0)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order within the report.')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_rejections', to='operations.riderweeklyreport')),
            ],
            options={
                'verbose_name': 'Sample rejection',
                'verbose_name_plural': 'Sample rejections',
                'ordering': ['report', 'order', 'pk'],
            },
        ),
    ]
