# Generated by Django 5.2.12 on 2026-04-08 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_samplerejection'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderweeklyreport',
            name='bike',
            field=models.ForeignKey(blank=True, help_text="Bike used for this report (must be in the rider's district).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekly_reports', to='operations.bike'),
        ),
    ]
