# Generated by Django 5.2.12 on 2026-04-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_riderweeklyreport_bike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ridertripentry',
            name='visit_purpose',
            field=models.CharField(blank=True, choices=[('sample_collection', 'Sample collection'), ('sample_delivery', 'Sample delivery'), ('adhoc', 'Ad hoc')], max_length=32),
        ),
    ]
