# Generated by Django 5.2.12 on 2026-04-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0008_ridertripentry_visit_purpose_adhoc'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderweeklyreport',
            name='scheduled_visits',
            field=models.PositiveIntegerField(blank=True, help_text='Number of visits scheduled for this week (entered by program coordinator).', null=True),
        ),
    ]
