# Generated by Django 5.2.12 on 2026-04-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0009_riderweeklyreport_scheduled_visits'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderweeklyreport',
            name='snp_bike_accident',
            field=models.PositiveIntegerField(default=0, help_text='Days: bike accident / damaged.'),
        ),
        migrations.AddField(
            model_name='riderweeklyreport',
            name='snp_bike_breakdown',
            field=models.PositiveIntegerField(default=0, help_text='Days: bike breakdown.'),
        ),
        migrations.AddField(
            model_name='riderweeklyreport',
            name='snp_bike_no_fuel',
            field=models.PositiveIntegerField(default=0, help_text='Days: bike had no fuel.'),
        ),
        migrations.AddField(
            model_name='riderweeklyreport',
            name='snp_bike_routine_service',
            field=models.PositiveIntegerField(default=0, help_text='Days: bike on routine service / maintenance.'),
        ),
        migrations.AddField(
            model_name='riderweeklyreport',
            name='snp_clinical_ip',
            field=models.PositiveIntegerField(default=0, help_text='Days: clinical IPs related issues.'),
        ),
        migrations.AddField(
            model_name='riderweeklyreport',
            name='snp_inclement_weather',
            field=models.PositiveIntegerField(default=0, help_text='Days: inclement weather.'),
        ),
        migrations.AddField(
            model_name='riderweeklyreport',
            name='snp_other',
            field=models.PositiveIntegerField(default=0, help_text='Days: other reasons (see specify).'),
        ),
        migrations.AddField(
            model_name='riderweeklyreport',
            name='snp_other_specify',
            field=models.CharField(blank=True, help_text='E.g. vacant post, rider reassigned, suspension, public holiday.', max_length=512),
        ),
        migrations.AddField(
            model_name='riderweeklyreport',
            name='snp_rider_annual_leave',
            field=models.PositiveIntegerField(default=0, help_text='Days: rider on annual leave.'),
        ),
        migrations.AddField(
            model_name='riderweeklyreport',
            name='snp_rider_sick_leave',
            field=models.PositiveIntegerField(default=0, help_text='Days: rider on sick leave.'),
        ),
    ]
