# Generated by Django 5.2.12 on 2026-04-08 13:47

from django.db import migrations, models


def copy_snp_from_reports_to_bikes(apps, schema_editor):
    RiderWeeklyReport = apps.get_model("operations", "RiderWeeklyReport")
    Bike = apps.get_model("operations", "Bike")
    bike_ids = (
        RiderWeeklyReport.objects.exclude(bike_id=None)
        .values_list("bike_id", flat=True)
        .distinct()
    )
    for bike_id in bike_ids:
        r = (
            RiderWeeklyReport.objects.filter(bike_id=bike_id)
            .order_by("-week_start", "-pk")
            .first()
        )
        if not r:
            continue
        Bike.objects.filter(pk=bike_id).update(
            snp_bike_breakdown=r.snp_bike_breakdown,
            snp_bike_routine_service=r.snp_bike_routine_service,
            snp_bike_no_fuel=r.snp_bike_no_fuel,
            snp_rider_sick_leave=r.snp_rider_sick_leave,
            snp_rider_annual_leave=r.snp_rider_annual_leave,
            snp_inclement_weather=r.snp_inclement_weather,
            snp_bike_accident=r.snp_bike_accident,
            snp_clinical_ip=r.snp_clinical_ip,
            snp_other=r.snp_other,
            snp_other_specify=r.snp_other_specify or "",
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0010_riderweeklyreport_snp_bike_accident_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bike",
            name="snp_bike_accident",
            field=models.PositiveIntegerField(default=0, help_text="Days: bike accident / damaged."),
        ),
        migrations.AddField(
            model_name="bike",
            name="snp_bike_breakdown",
            field=models.PositiveIntegerField(default=0, help_text="Days: bike breakdown."),
        ),
        migrations.AddField(
            model_name="bike",
            name="snp_bike_no_fuel",
            field=models.PositiveIntegerField(default=0, help_text="Days: bike had no fuel."),
        ),
        migrations.AddField(
            model_name="bike",
            name="snp_bike_routine_service",
            field=models.PositiveIntegerField(default=0, help_text="Days: bike on routine service / maintenance."),
        ),
        migrations.AddField(
            model_name="bike",
            name="snp_clinical_ip",
            field=models.PositiveIntegerField(default=0, help_text="Days: clinical IPs related issues."),
        ),
        migrations.AddField(
            model_name="bike",
            name="snp_inclement_weather",
            field=models.PositiveIntegerField(default=0, help_text="Days: inclement weather."),
        ),
        migrations.AddField(
            model_name="bike",
            name="snp_other",
            field=models.PositiveIntegerField(default=0, help_text="Days: other reasons (see specify)."),
        ),
        migrations.AddField(
            model_name="bike",
            name="snp_other_specify",
            field=models.CharField(
                blank=True,
                help_text="E.g. vacant post, rider reassigned, suspension, public holiday.",
                max_length=512,
            ),
        ),
        migrations.AddField(
            model_name="bike",
            name="snp_rider_annual_leave",
            field=models.PositiveIntegerField(default=0, help_text="Days: rider on annual leave."),
        ),
        migrations.AddField(
            model_name="bike",
            name="snp_rider_sick_leave",
            field=models.PositiveIntegerField(default=0, help_text="Days: rider on sick leave."),
        ),
        migrations.RunPython(copy_snp_from_reports_to_bikes, noop_reverse),
        migrations.RemoveField(
            model_name="riderweeklyreport",
            name="snp_bike_accident",
        ),
        migrations.RemoveField(
            model_name="riderweeklyreport",
            name="snp_bike_breakdown",
        ),
        migrations.RemoveField(
            model_name="riderweeklyreport",
            name="snp_bike_no_fuel",
        ),
        migrations.RemoveField(
            model_name="riderweeklyreport",
            name="snp_bike_routine_service",
        ),
        migrations.RemoveField(
            model_name="riderweeklyreport",
            name="snp_clinical_ip",
        ),
        migrations.RemoveField(
            model_name="riderweeklyreport",
            name="snp_inclement_weather",
        ),
        migrations.RemoveField(
            model_name="riderweeklyreport",
            name="snp_other",
        ),
        migrations.RemoveField(
            model_name="riderweeklyreport",
            name="snp_other_specify",
        ),
        migrations.RemoveField(
            model_name="riderweeklyreport",
            name="snp_rider_annual_leave",
        ),
        migrations.RemoveField(
            model_name="riderweeklyreport",
            name="snp_rider_sick_leave",
        ),
    ]
