# Generated by Django 5.2.12 on 2026-04-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0011_move_snp_fields_to_bike'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='mitigation_measures',
            field=models.TextField(blank=True, help_text='Actions taken to address bike or specimen non-pickup issues.'),
        ),
    ]
