# Generated by Django 5.2.12 on 2026-04-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0012_bike_mitigation_measures'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderweeklyreport',
            name='average_datalogger_temperature',
            field=models.IntegerField(blank=True, help_text='Average data logger temperature for this reporting week (whole number, e.g. °C).', null=True),
        ),
    ]
