# Generated by Django 5.2.12 on 2026-04-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0013_riderweeklyreport_average_datalogger_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='affected_facilities',
            field=models.ManyToManyField(blank=True, help_text="Facilities in this bike's district impacted by specimen non-pickup or related issues.", related_name='affected_bikes', to='operations.facility'),
        ),
    ]
