# Generated by Django 5.2.12 on 2026-04-08 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0014_bike_affected_facilities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('notes', models.CharField(blank=True, max_length=256)),
                ('active', models.BooleanField(default=True)),
                ('snp_bike_breakdown', models.PositiveIntegerField(default=0, help_text='Days: vehicle breakdown.')),
                ('snp_bike_routine_service', models.PositiveIntegerField(default=0, help_text='Days: vehicle on routine service / maintenance.')),
                ('snp_bike_no_fuel', models.PositiveIntegerField(default=0, help_text='Days: vehicle had no fuel.')),
                ('snp_rider_sick_leave', models.PositiveIntegerField(default=0, help_text='Days: driver on sick leave.')),
                ('snp_rider_annual_leave', models.PositiveIntegerField(default=0, help_text='Days: driver on annual leave.')),
                ('snp_inclement_weather', models.PositiveIntegerField(default=0, help_text='Days: inclement weather.')),
                ('snp_bike_accident', models.PositiveIntegerField(default=0, help_text='Days: vehicle accident / damaged.')),
                ('snp_clinical_ip', models.PositiveIntegerField(default=0, help_text='Days: clinical IPs related issues.')),
                ('snp_other', models.PositiveIntegerField(default=0, help_text='Days: other reasons (see specify).')),
                ('snp_other_specify', models.CharField(blank=True, help_text='E.g. vacant post, driver reassigned, suspension, public holiday.', max_length=512)),
                ('mitigation_measures', models.TextField(blank=True, help_text='Actions taken to address vehicle or specimen non-pickup issues.')),
                ('affected_facilities', models.ManyToManyField(blank=True, help_text="Facilities in this vehicle's district impacted by specimen non-pickup or related issues.", related_name='affected_cars', to='operations.facility')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='operations.district')),
            ],
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_profiles', to='operations.car'),
        ),
        migrations.AddField(
            model_name='riderweeklyreport',
            name='car',
            field=models.ForeignKey(blank=True, help_text='Vehicle (car) for driver reports when applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekly_reports', to='operations.car'),
        ),
    ]
