# Generated by Django 5.2.12 on 2026-04-08 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0018_driver_legacy_trips_to_relayed'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='site_code',
            field=models.CharField(blank=True, help_text='PEPFAR / site identifier for reports (e.g. lab line: District - code - name).', max_length=32),
        ),
        migrations.CreateModel(
            name='ReferredSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_type', models.CharField(choices=[('dbs', 'DBS'), ('plasma', 'Plasma'), ('blood', 'Blood'), ('other', 'Other')], max_length=32)),
                ('test_type', models.CharField(choices=[('vl', 'VL'), ('eid', 'EID'), ('hpv', 'HPV'), ('tb', 'TB'), ('other', 'Other')], max_length=32)),
                ('total_samples_referred_out', models.PositiveIntegerField(default=0)),
                ('swift_consignment_number', models.CharField(blank=True, help_text='Swift consignment / tracking reference.', max_length=64)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_facility', models.ForeignKey(help_text='Lab (referring site).', on_delete=django.db.models.deletion.CASCADE, related_name='referred_samples_out', to='operations.facility')),
                ('to_facility', models.ForeignKey(blank=True, help_text='Reference lab samples were referred to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_samples_in', to='operations.facility')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
