# Generated by Django 5.2.12 on 2026-04-08 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0019_facility_site_code_and_referred_sample'),
    ]

    operations = [
        migrations.CreateModel(
            name='PCDistrictWeeklyTransportStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(db_index=True)),
                ('rider_accidents', models.PositiveIntegerField(default=0)),
                ('incomplete_bike_transport_trips', models.PositiveIntegerField(default=0)),
                ('specimens_non_ist_total', models.PositiveIntegerField(default=0, help_text='Total specimens transported by non-IST methods.')),
                ('specimens_ambulance', models.PositiveIntegerField(default=0)),
                ('specimens_alternative_ip_transport', models.PositiveIntegerField(default=0)),
                ('specimens_mohcc_arranged_transport', models.PositiveIntegerField(default=0)),
                ('specimens_courier', models.PositiveIntegerField(default=0)),
                ('specimens_other_non_ist', models.PositiveIntegerField(default=0)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pc_weekly_transport_stats', to='operations.district')),
            ],
            options={
                'ordering': ['district__province_id', 'district__name', 'id'],
                'constraints': [models.UniqueConstraint(fields=('week_start', 'district'), name='uniq_pc_district_week_transport_stat')],
            },
        ),
    ]
