# Generated by Django 6.0.4 on 2026-04-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0021_lab_riderdevice_riderremoteconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ridertripentry',
            name='transport_kind',
            field=models.CharField(choices=[('legacy', 'Legacy (rider / historical)'), ('relayed', 'Samples relayed (not carried for the first time)'), ('first_transport', 'Samples transported for the first time')], db_index=True, default='legacy', max_length=32),
        ),
    ]
