# Generated by Django 5.2.12 on 2026-05-04 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0022_alter_ridertripentry_transport_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='PCAccidentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(db_index=True)),
                ('accident_cause', models.TextField(blank=True)),
                ('bike_status', models.PositiveSmallIntegerField(choices=[(1, 'Working'), (2, 'Minor damage'), (3, 'Write off'), (4, 'Major damaged')], default=1)),
                ('rider_injury_status', models.PositiveSmallIntegerField(choices=[(1, 'Minor injuries'), (2, 'Major injuries'), (3, 'Dead')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pc_accident_details', to='operations.bike')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pc_accident_details', to='operations.riderprofile')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
