# Generated by Django 5.2.12 on 2026-05-04 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0023_pcaccidentdetail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='riderweeklyreport',
            name='me_reviewed_at',
            field=models.DateTimeField(blank=True, help_text='When set, M&E has finalized review of this report and PCs may no longer edit it.', null=True),
        ),
        migrations.AddField(
            model_name='riderweeklyreport',
            name='me_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_me_reviewed', to=settings.AUTH_USER_MODEL),
        ),
    ]
