# Generated by Django 5.2.12 on 2026-05-08 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0024_riderweeklyreport_me_review'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='riderweeklyreport',
            name='uniq_rider_week',
        ),
    ]
